name: Format and Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  format-upgrade-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: make install
          
      - name: Run formatters
        run: make format

      - name: Run upgraders
        run: make upgrade
          
      - name: Run linter
        run: make lint
          
      - name: Commit and push changes if any
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A
            git commit -m "style: format code with black and isort"
            git push
          else
            echo "No changes to commit"
          fi
